repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
  - id: check-docstring-first
  - id: check-vcs-permalinks
  - id: check-yaml
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: mixed-line-ending
    args: ["--fix=lf"]
  - id: pretty-format-json
    args: ["--autofix"]
- repo: local
  hooks:
    - id: make-test
      name: make-test
      entry: make test
      language: system
      pass_filenames: false
