blank_issues_enabled: false
contact_links:
  - name: "Пустой баг репорт"
    url: https://github.com/{{ cookiecutter.organization }}/{{ cookiecutter.project_name }}/issues/new
    about: Только для участников репозитория.

