blank_issues_enabled: false
contact_links:
  - name: "Empty Issue"
    url: https://github.com/{{ cookiecutter.organization }}/{{ cookiecutter.project_name }}/issues/new
    about: Only for maintainers.

